### PR TITLE
use requests instead of urllib{,2,3} directly where possible

### PR DESCRIPTION
**Pull request by emu-signal**
This gets rid of the necessity for most of the 'if PYTHON_VERSION...'
cruft, as well as cleaning up the code around the requests themselves.

I'm certain that there is more tidying to do here, but for now, this
seems to work for all the endpoints I've tried, on both python3.4.3 and
python2.7.9 against my v4 controller.

### CODE REVIEW

**Comment by calmh** [comment]
The requests package is nice, but it's also a new external dependency. Is this fine everywhere unifi-api may be used?

**Comment by emu-signal** [comment]
My python experience is fairly limited, so it's hard for me to argue a technical reason for or against. That being said, it's hard to imagine a python installation that didn't cater for even a local install of requests but did allow for this library to be installed.

I mostly did this because I was trying to integrate my Unifi AP into an installation of [home-assistant](http://github.com/balloob/home-assistant) and had difficulty trying to get it to work out of the box. It was as much a matter of personal taste and ignorance as anything else.

Either way, if and when you're happy with this, it might be worth tagging beforehand; or, if you'd rather not take the dependency I can just maintain my own fork.

**Comment by emu-signal** [comment]
For whatever it's worth, my changes to home-assistant [are here](https://github.com/emu-signal/home-assistant/tree/add-unifi-device_tracker).

**Comment by flyte** [comment]
I'd vote for requests, myself. Along with the benefits @emu-signal mentioned, [here are a few more](https://stackoverflow.com/questions/2018026/should-i-use-urllib-urllib2-or-requests) to convince you!

**Comment by fxstein** [comment]
+1 on the requests implementation. It's becoming the defacto standard for all kinds of web based communications. Very well designed, easy to implement and read after the fact.

I just had to pull config and statistics data from a set of ToughSwitches and even though they lack an official API, requests made it very easy to hook into the existing Ajax end points.
https://github.com/fxstein/SentientHome/blob/master/feed/feed.home.ubnt.toughswitch.py

**Comment by dsully** [comment]
+1

**Comment by calmh** [comment]
Ok, lets get the conflicts resolved and this merged. I'm convinced, sorry for dragging my feet.

**Comment by fxstein** [comment]
Awesome!

**Pull request closed without merging**
