### PR TITLE
add controller sites getter get_sites()

### PR DESCRIPTION
**Pull request by oe1rfc**

### CODE REVIEW

**Comment by artooro** [comment]
Is it possible to add a method called create_site as well? Or does the unifi API not provide that capability?

**Comment by calmh** [comment]
Is this the cleanest way to do this? It seems to me like it may be time to refactor this API to take into account the changes that have happened server side (like the introduction of sites). That is, most of these methods should instead belong on a `site` type, which is returned by a `get_site` method? For legacy installations, some kind of empty default site could be provided?

**Comment by artooro** [comment]
I ended up writing my own code to interact with the unifi API because I needed to create and manage sites as well as enrol new devices using the API. So functions include create site, list sites, list waiting to enrol devices, and of course authentication.

**Comment by uJIu4** [comment]
`    def get_sites(self):
        """Return a list of all Sites (UniFi >= 3.x)."""
        if(self.version == 'v2'):
            return None
        elif(self.version == 'v3'):
            js = json.dumps({'cmd':'get-sites'})
            params = urllib.urlencode({'json': js})
            return self._read(self.api_url + 'cmd/sitemgr', params)            
        else:
            return self._read(self.url + 'api/self/sites')
`

**Pull request closed without merging**
